# Generated by Django 4.2.4 on 2023-09-04 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('date_time', models.DateTimeField()),
                ('class_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.student_class')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('class_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.student_class')),
            ],
        ),
    ]
