# Generated by Django 4.2.4 on 2023-09-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='class_student',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='marks',
        ),
        migrations.CreateModel(
            name='Quiz_Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('class_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.student_class')),
                ('quiz_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.quiz')),
            ],
        ),
    ]
