# Generated by Django 4.2.4 on 2023-09-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('Teacher', '0002_rename_quiz_name_quiz_name_remove_quiz_class_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='class_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='administrator.class'),
            preserve_default=False,
        ),
    ]
