# Generated by Django 4.2.4 on 2023-09-09 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('Teacher', '0003_quiz_class_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='class_student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.class'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Attendance_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=100)),
                ('attendance_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.attendance')),
                ('class_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.student_class')),
            ],
        ),
    ]
