# Generated by Django 4.2.3 on 2023-08-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('class_taught', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.class')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.class')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.teacher')),
            ],
        ),
    ]
