# Generated by Django 4.2.3 on 2023-08-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_taught',
        ),
    ]
