# Generated by Django 4.2.4 on 2023-08-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_teacher_class_taught'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('gardian_or_parent_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_enrollment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.student')),
            ],
        ),
    ]
