# Generated by Django 4.2.3 on 2023-08-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_teacher_class_taught'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_class',
            old_name='class_id',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='teacher_class',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
